#ifndef __CTRL_INV_H
#define __CTRL_INV_H

#include "pfc_hardware.h"
#include "my_math.h"

#define CTRL_INV_FREQ 50.0f
#define CTRL_INV_RMS 230.0f

#define INV_VOLT_LOOP_FREQ_CUT 300.0f
#define INV_VOLT_LOOP_PM 60.0f

#define INV_VOLT_LOOP_D_FREQ_CUT INV_VOLT_LOOP_FREQ_CUT
#define INV_VOLT_LOOP_D_W_CUT (2.0f * M_PI * INV_VOLT_LOOP_D_FREQ_CUT)
#define INV_VOLT_LOOP_D_PM INV_VOLT_LOOP_PM
#define INV_VOLT_LOOP_D_KP (sinf(INV_VOLT_LOOP_D_PM / 180.0f * M_PI) * INV_VOLT_LOOP_D_W_CUT * CAP_INV_VALUE)
#define INV_VOLT_LOOP_D_KI /* 0.0f // */(INV_VOLT_LOOP_D_KP * INV_VOLT_LOOP_D_W_CUT / tanf(INV_VOLT_LOOP_D_PM / 180.0f * M_PI))

#define INV_VOLT_LOOP_Q_FREQ_CUT INV_VOLT_LOOP_FREQ_CUT
#define INV_VOLT_LOOP_Q_W_CUT (2.0f * M_PI * INV_VOLT_LOOP_Q_FREQ_CUT)
#define INV_VOLT_LOOP_Q_PM INV_VOLT_LOOP_PM
#define INV_VOLT_LOOP_Q_KP (sinf(INV_VOLT_LOOP_Q_PM / 180.0f * M_PI) * INV_VOLT_LOOP_Q_W_CUT * CAP_INV_VALUE)
#define INV_VOLT_LOOP_Q_KI /* 0.0f // */(INV_VOLT_LOOP_Q_KP * INV_VOLT_LOOP_Q_W_CUT / tanf(INV_VOLT_LOOP_Q_PM / 180.0f * M_PI))

#define INV_CURR_LOOP_FREQ_CUT 2500.0f
#define INV_CURR_LOOP_PM 60.0f

#define INV_CURR_LOOP_D_FREQ_CUT INV_CURR_LOOP_FREQ_CUT
#define INV_CURR_LOOP_D_W_CUT (2.0f * M_PI * INV_CURR_LOOP_D_FREQ_CUT)
#define INV_CURR_LOOP_D_PM INV_CURR_LOOP_PM
#define INV_CURR_LOOP_D_KP (sinf(INV_CURR_LOOP_D_PM / 180.0f * M_PI) * INV_CURR_LOOP_D_W_CUT * L_PFC_VALUE)
#define INV_CURR_LOOP_D_KI 0.0f //(INV_CURR_LOOP_D_KP * INV_CURR_LOOP_D_W_CUT / tanf(INV_CURR_LOOP_D_PM / 180.0f * M_PI))

#define INV_CURR_LOOP_Q_FREQ_CUT INV_CURR_LOOP_FREQ_CUT
#define INV_CURR_LOOP_Q_W_CUT (2.0f * M_PI * INV_CURR_LOOP_Q_FREQ_CUT)
#define INV_CURR_LOOP_Q_PM INV_CURR_LOOP_PM
#define INV_CURR_LOOP_Q_KP (sinf(INV_CURR_LOOP_Q_PM / 180.0f * M_PI) * INV_CURR_LOOP_Q_W_CUT * L_PFC_VALUE)
#define INV_CURR_LOOP_Q_KI 0.0f //(INV_CURR_LOOP_Q_KP * INV_CURR_LOOP_Q_W_CUT / tanf(INV_CURR_LOOP_Q_PM / 180.0f * M_PI))

void ctrl_inv_enable(void);

void ctrl_inv_disable(void);

#endif
