#ifndef __PLECS_H
#define __PLECS_H

#include "stdint.h"

typedef enum
{
#if defined(IS_BUCK)
    PLECS_INPUT_HV = 0,
    PLECS_INPUT_LV,
    PLECS_INPUT_ILA,
    PLECS_INPUT_ILB,
    PLECS_INPUT_RUN,
    PLECS_INPUT_PWR_LMT,
    PLECS_INPUT_IN_CURR_LMT,
    PLECS_INPUT_OUT_CURR_LMT,
    PLECS_INPUT_OUT_VOLT_REF,
#else
    PLECS_INPUT_I_L,
    PLECS_INPUT_V_CAP,
    PLECS_INPUT_V_BUS,
    PLECS_INPUT_V_G,
    PLECS_INPUT_I_OUT,
    PLECS_INPUT_V_OUT,
    PLECS_INPUT_MODE,
#endif
    PLECS_INPUT_MAX,
} PLECS_INPUT_E;

typedef enum
{
#if defined(IS_BUCK)
    PLECS_OUTPUT_PWM_A_DUTY = 0,
    PLECS_OUTPUT_PWM_A_CMP,
    PLECS_OUTPUT_PWM_A_UP_EN,
    PLECS_OUTPUT_PWM_A_DN_EN,
    PLECS_OUTPUT_PWM_B_DUTY,
    PLECS_OUTPUT_PWM_B_CMP,
    PLECS_OUTPUT_PWM_B_UP_EN,
    PLECS_OUTPUT_PWM_B_DN_EN,
    PLECS_OUTPUT_RUN_STATE,
    PLECS_OUTPUT_HV_CODE,
    PLECS_OUTPUT_LV_CODE,
    PLECS_OUTPUT_ILA_CODE,
    PLECS_OUTPUT_ILB_CODE,
    PLECS_OUTPUT_MAX,
#else
    PLECS_OUTPUT_PWM_FAST_DUTY,
    PLECS_OUTPUT_PWM_FAST_UP_EN,
    PLECS_OUTPUT_PWM_FAST_DN_EN,
    PLECS_OUTPUT_PWM_SLOW_DUTY,
    PLECS_OUTPUT_PWM_SLOW_UP_EN,
    PLECS_OUTPUT_PWM_SLOW_DN_EN,
    PLECS_OUTPUT_AC_OUT_RLY_EN,
    PLECS_OUTPUT_MAIN_RLY_EN,
    PLECS_OUTPUT_DBG,
    PLECS_OUTPUT_MAX = 30,
#endif
} PLECS_OUTPUT_E;

#define PLECS_INPUT_NUM PLECS_INPUT_MAX
#define PLECS_OUTPUT_NUM PLECS_OUTPUT_MAX

float plecs_get_input(PLECS_INPUT_E num);
void plecs_set_output(PLECS_OUTPUT_E num, float val);

void plecs_printf(const char *file, int line, const char *format, ...);

#define PLECS_LOG(...) plecs_printf(__FILE__, __LINE__, __VA_ARGS__)

extern uint32_t plecs_time_100us;

#endif
