#ifndef __INV_CTRL_H
#define __INV_CTRL_H

#include "inv_hal.h"
#include "hw_params.h"
#include "my_math.h"

#define INV_CTRL_VOLT_LOOP_FREQ_CUT (300.0f)
#define INV_CTRL_VOLT_LOOP_PM (60.0f)

#define INV_CTRL_VOLT_LOOP_D_FREQ_CUT INV_CTRL_VOLT_LOOP_FREQ_CUT
#define INV_CTRL_VOLT_LOOP_D_W_CUT (2.0f * M_PI * INV_CTRL_VOLT_LOOP_D_FREQ_CUT)
#define INV_CTRL_VOLT_LOOP_D_PM INV_CTRL_VOLT_LOOP_PM
#define INV_CTRL_VOLT_LOOP_D_KP (sinf(INV_CTRL_VOLT_LOOP_D_PM / 180.0f * M_PI) * INV_CTRL_VOLT_LOOP_D_W_CUT * HW_AC_SIDE_CAP_VALUE)
#define INV_CTRL_VOLT_LOOP_D_KI (INV_CTRL_VOLT_LOOP_D_KP * INV_CTRL_VOLT_LOOP_D_W_CUT / tanf(INV_CTRL_VOLT_LOOP_D_PM / 180.0f * M_PI))

#define INV_CTRL_VOLT_LOOP_Q_FREQ_CUT INV_CTRL_VOLT_LOOP_FREQ_CUT
#define INV_CTRL_VOLT_LOOP_Q_W_CUT (2.0f * M_PI * INV_CTRL_VOLT_LOOP_Q_FREQ_CUT)
#define INV_CTRL_VOLT_LOOP_Q_PM INV_CTRL_VOLT_LOOP_PM
#define INV_CTRL_VOLT_LOOP_Q_KP (sinf(INV_CTRL_VOLT_LOOP_Q_PM / 180.0f * M_PI) * INV_CTRL_VOLT_LOOP_Q_W_CUT * HW_AC_SIDE_CAP_VALUE)
#define INV_CTRL_VOLT_LOOP_Q_KI (INV_CTRL_VOLT_LOOP_Q_KP * INV_CTRL_VOLT_LOOP_Q_W_CUT / tanf(INV_CTRL_VOLT_LOOP_Q_PM / 180.0f * M_PI))

#define INV_CTRL_CURR_LOOP_FREQ_CUT (1500.0f)
#define INV_CTRL_CURR_LOOP_PM (45.0f)

#define INV_CTRL_CURR_LOOP_D_FREQ_CUT INV_CTRL_CURR_LOOP_FREQ_CUT
#define INV_CTRL_CURR_LOOP_D_W_CUT (2.0f * M_PI * INV_CTRL_CURR_LOOP_D_FREQ_CUT)
#define INV_CTRL_CURR_LOOP_D_PM INV_CTRL_CURR_LOOP_PM
#define INV_CTRL_CURR_LOOP_D_KP (sinf(INV_CTRL_CURR_LOOP_D_PM / 180.0f * M_PI) * INV_CTRL_CURR_LOOP_D_W_CUT * HW_AC_SIDE_IND_VALUE)
#define INV_CTRL_CURR_LOOP_D_KI (0.0f)

#define INV_CTRL_CURR_LOOP_Q_FREQ_CUT INV_CTRL_CURR_LOOP_FREQ_CUT
#define INV_CTRL_CURR_LOOP_Q_W_CUT (2.0f * M_PI * INV_CTRL_CURR_LOOP_Q_FREQ_CUT)
#define INV_CTRL_CURR_LOOP_Q_PM INV_CTRL_CURR_LOOP_PM
#define INV_CTRL_CURR_LOOP_Q_KP (sinf(INV_CTRL_CURR_LOOP_Q_PM / 180.0f * M_PI) * INV_CTRL_CURR_LOOP_Q_W_CUT * HW_AC_SIDE_IND_VALUE)
#define INV_CTRL_CURR_LOOP_Q_KI (0.0f)

void inv_ctrl_set_p_hal(inv_ctrl_hal_t *p);
void inv_ctrl_prepare_run(void);

#endif
