#ifndef __COMM_LINK_H
#define __COMM_LINK_H

#include "platform.h"

#define COMM_LINK_ENABLE_ISO PLATFORM_COMM_LINK_ENABLE_ISO
#define COMM_LINK_ENABLE_CAN PLATFORM_COMM_LINK_ENABLE_CAN

typedef enum
{
    USART0_LINK,
    USART1_LINK,
    USART2_LINK,
    USART_DBG_LINK,
    USART_ISO_LINK,
    USART4_LINK,
    UART4_LINK = USART4_LINK,
    CAN_DBG_LINK,
} USART_LINK_E;

#endif
