%% CLLC 正向和反向不同功率下的频率增益分析
% 使用基波近似法（Fundamental Harmonic Approximation, FHA）计算图示
% CLLC 谐振网络在正向、反向功率流下的频率增益曲线。
%
% 默认工况：
%   - 正向功率流：原边 450 V -> 副边 48 V
%   - 反向功率流：副边 48 V -> 原边 450 V
%   - 输入侧全桥驱动，输出侧全桥整流/同步整流
%   - 忽略开关管压降、死区、绕组电阻和磁性元件损耗
%
% 增益定义：
%   G = Vout / Vin
%   正向归一化增益 M_forward = n * G_forward
%   反向归一化增益 M_reverse = G_reverse / n
%   其中 n = Np / Ns
%
% 对全桥整流和恒压输出，输出侧 FHA 等效交流负载为：
%   Rac = 8 / pi^2 * Vout^2 / Pout
%
% 控制环路波特图参考论文 Energies 2023, 16, 7173 的式 (13)-(16)：
%   - 被控对象：Gvf(s) = Delta Vout(s) / Delta fs(s)
%   - 控制器：Gc(s) = Kp + Ki/s
%   - 开环：T(s) = Gc(s) * Gvf(s)
%   - PI 零点设置为目标交越频率的 0.1 倍
%   - 2P2Z：K*(1+s/wz)^2/[s*(1+s/wp)^2]
%     参数 K、fz、fp 与 code/lib/z2p2_init() 的连续原型一致
%
% 论文通过小信号模型和计算机仿真获得功率级。本脚本在缺少实测
% FRA/PLECS AC Sweep 数据时，使用 FHA 稳态增益斜率和输出电容功率
% 平衡建立低频包络近似。该模型适合初步控制器设计，最终参数应由
% PLECS 小信号注入或硬件 FRA 结果校核。

clear;
clc;
close all;

%% 用户可调参数
Vin_forward = 450;                 % 正向输入直流电压 / V
Vout_forward = 48;                 % 正向输出直流电压 / V
Vin_reverse = 48;                  % 反向输入直流电压 / V
Vout_reverse = 450;                % 反向输出直流电压 / V
power_w = [100, 500, 1000, 2000, 3000, ...
           4000, 5000, 6000, 6600]; % 输出功率点 / W

frequency_hz = linspace(20e3, 260e3, 4801); % 计算扫频范围 / Hz
forward_plot_range_hz = [40e3, 260e3];
reverse_plot_range_hz = [20e3, 120e3];

% 调频控制环路参数
Cout_forward = 10000e-6;           % PLECS 正向低压侧输出电容 / F
Cout_reverse = 1360e-6;            % PLECS 反向高压侧输出电容 / F
control_frequency_hz = logspace(-2, 5, 2801); % 环路扰动频率 / Hz
control_plot_range_hz = [0.1, 30e3];
controller_crossover_hz = 3.5e3;  % 论文 PFM 示例交越频率 / Hz
controller_zero_ratio = 0.1;       % fz/fc，来自论文式 (16)
forward_controller_design_power_w = 6600;
reverse_controller_design_power_w = 4000;
control_delay_cycles = 1;          % 调制与数字更新等效延迟 / 开关周期
z2p2_target_phase_margin_deg = 50; % 兼顾 PM 与 GM 的设计点目标
z2p2_target_gain_margin_db = 6;
z2p2_min_crossover_ratio = 0.2;    % 最低搜索到 PI 目标带宽的比例
z2p2_max_pole_fs_ratio = 0.2;      % 高频极点不超过最低工作 fs 的比例

% 图中 CLLC 谐振网络参数
Lr_primary = 40e-6;                % 原边串联谐振电感 / H
Cr_primary = 80e-9;                % 原边串联谐振电容 / F
Lm_primary = 200e-6;               % 原边励磁电感 / H
Lr_secondary = 0.625e-6;           % 副边串联谐振电感 / H
Cr_secondary = 5.12e-6;            % 副边串联谐振电容 / F

Np = 24;                           % 原边匝数
Ns = 3;                            % 副边匝数
n = Np / Ns;                       % 原副边匝数比

%% 正向和反向 FHA 等效负载
Rload_dc_forward = Vout_forward^2 ./ power_w;
Rload_ac_forward = (8 / pi^2) .* Rload_dc_forward;

Rload_dc_reverse = Vout_reverse^2 ./ power_w;
Rload_ac_reverse = (8 / pi^2) .* Rload_dc_reverse;

%% 谐振元件阻抗
omega = 2 * pi * frequency_hz(:);

Zr_primary = 1j .* omega .* Lr_primary + ...
             1 ./ (1j .* omega .* Cr_primary);
Zm_primary = 1j .* omega .* Lm_primary;
Zr_secondary = 1j .* omega .* Lr_secondary + ...
               1 ./ (1j .* omega .* Cr_secondary);

%% 正向频率增益：原边输入，副边输出
% 每一列对应一个输出功率点。副边串联支路折算到原边后，与励磁
% 电感并联。
Zsecondary_total_forward = Zr_secondary + Rload_ac_forward;
Zsecondary_referred_forward = n^2 .* Zsecondary_total_forward;
Zparallel_forward = ...
    (Zm_primary .* Zsecondary_referred_forward) ./ ...
    (Zm_primary + Zsecondary_referred_forward);

% H_primary：原边谐振腔输入到变压器原边端口的传递函数。
% H_secondary：变压器副边端口到 FHA 等效交流负载的传递函数。
H_primary_forward = Zparallel_forward ./ ...
                    (Zr_primary + Zparallel_forward);
H_secondary_forward = Rload_ac_forward ./ ...
                      Zsecondary_total_forward;
H_vout_vin_forward = ...
    H_primary_forward .* H_secondary_forward ./ n;

gain_dc_forward = abs(H_vout_vin_forward);
gain_normalized_forward = n .* gain_dc_forward;

%% 反向频率增益：副边输入，原边输出
% 原边输出负载与原边谐振支路串联，该支路与励磁电感并联后再折算
% 到副边。励磁电感始终位于物理原边，反向增益不能由正向增益直接
% 取倒数得到。
Zprimary_total_reverse = Zr_primary + Rload_ac_reverse;
Zparallel_primary_reverse = ...
    (Zm_primary .* Zprimary_total_reverse) ./ ...
    (Zm_primary + Zprimary_total_reverse);
Zparallel_referred_secondary_reverse = ...
    Zparallel_primary_reverse ./ n^2;

H_secondary_reverse = Zparallel_referred_secondary_reverse ./ ...
    (Zr_secondary + Zparallel_referred_secondary_reverse);
H_primary_reverse = Rload_ac_reverse ./ Zprimary_total_reverse;
H_vout_vin_reverse = ...
    H_secondary_reverse .* H_primary_reverse .* n;

gain_dc_reverse = abs(H_vout_vin_reverse);
gain_normalized_reverse = gain_dc_reverse ./ n;

%% 特征频率与目标增益
fr_primary_hz = 1 / (2 * pi * sqrt(Lr_primary * Cr_primary));
fr_secondary_hz = 1 / (2 * pi * sqrt(Lr_secondary * Cr_secondary));

target_gain_dc_forward = Vout_forward / Vin_forward;
target_gain_normalized_forward = n * target_gain_dc_forward;
target_gain_dc_reverse = Vout_reverse / Vin_reverse;
target_gain_normalized_reverse = target_gain_dc_reverse / n;

frequency_forward_hz = nan(size(power_w));
frequency_reverse_hz = nan(size(power_w));
for k = 1:numel(power_w)
    frequency_forward_hz(k) = find_gain_crossing( ...
        frequency_hz, gain_normalized_forward(:, k), ...
        target_gain_normalized_forward, fr_primary_hz, 'above');
    frequency_reverse_hz(k) = find_gain_crossing( ...
        frequency_hz, gain_normalized_reverse(:, k), ...
        target_gain_normalized_reverse, fr_primary_hz, 'below');
end

[max_gain_reverse, max_gain_reverse_index] = ...
    max(gain_normalized_reverse, [], 1);
max_gain_reverse_frequency_hz = ...
    frequency_hz(max_gain_reverse_index);

operating_points_forward = table( ...
    power_w(:), Rload_dc_forward(:), Rload_ac_forward(:), ...
    frequency_forward_hz(:) / 1e3, ...
    'VariableNames', { ...
        'Power_W', 'RloadDC_Ohm', 'RloadAC_Ohm', ...
        'FrequencyAboveResonance_kHz'});

operating_points_reverse = table( ...
    power_w(:), Rload_dc_reverse(:), Rload_ac_reverse(:), ...
    max_gain_reverse(:), max_gain_reverse_frequency_hz(:) / 1e3, ...
    frequency_reverse_hz(:) / 1e3, ...
    'VariableNames', { ...
        'Power_W', 'RloadDC_Ohm', 'RloadAC_Ohm', ...
        'MaximumNormalizedGain', 'MaximumGainFrequency_kHz', ...
        'FrequencyBelowResonance_kHz'});

%% PFM 调频控制小信号被控对象
% 在固定电阻负载下，由 FHA 稳态曲线求工作点增益斜率 Kvf。输出端
% 使用功率平衡线性化得到 tau = Rload*Cout/2。频率执行方向定义为
% fs = fs_bias - u，因此在正常负斜率工作区内，环路被控对象为正增益。
static_output_voltage_forward = Vin_forward .* gain_dc_forward;
static_output_voltage_reverse = Vin_reverse .* gain_dc_reverse;

[plant_forward, Kvf_forward, output_tau_forward_s] = ...
    build_pfm_control_plant( ...
        control_frequency_hz, frequency_hz, ...
        static_output_voltage_forward, frequency_forward_hz, ...
        Rload_dc_forward, Cout_forward, control_delay_cycles);
[plant_reverse, Kvf_reverse, output_tau_reverse_s] = ...
    build_pfm_control_plant( ...
        control_frequency_hz, frequency_hz, ...
        static_output_voltage_reverse, frequency_reverse_hz, ...
        Rload_dc_reverse, Cout_reverse, control_delay_cycles);

[~, forward_design_index] = min(abs( ...
    power_w - forward_controller_design_power_w));
[~, reverse_design_index] = min(abs( ...
    power_w - reverse_controller_design_power_w));

[Kp_forward, Ki_forward, controller_forward] = ...
    design_pi_controller( ...
        control_frequency_hz, plant_forward(:, forward_design_index), ...
        controller_crossover_hz, controller_zero_ratio);
[Kp_reverse, Ki_reverse, controller_reverse] = ...
    design_pi_controller( ...
        control_frequency_hz, plant_reverse(:, reverse_design_index), ...
        controller_crossover_hz, controller_zero_ratio);

[K_z2p2_forward, fz_z2p2_forward_hz, fp_z2p2_forward_hz, ...
 controller_z2p2_forward, crossover_z2p2_forward_hz] = ...
    design_z2p2_controller( ...
    control_frequency_hz, plant_forward(:, forward_design_index), ...
    controller_crossover_hz, output_tau_forward_s(forward_design_index), ...
    frequency_forward_hz, z2p2_target_phase_margin_deg, ...
    z2p2_target_gain_margin_db, z2p2_min_crossover_ratio, ...
    z2p2_max_pole_fs_ratio);
[K_z2p2_reverse, fz_z2p2_reverse_hz, fp_z2p2_reverse_hz, ...
 controller_z2p2_reverse, crossover_z2p2_reverse_hz] = ...
    design_z2p2_controller( ...
    control_frequency_hz, plant_reverse(:, reverse_design_index), ...
    controller_crossover_hz, output_tau_reverse_s(reverse_design_index), ...
    frequency_reverse_hz, z2p2_target_phase_margin_deg, ...
    z2p2_target_gain_margin_db, z2p2_min_crossover_ratio, ...
    z2p2_max_pole_fs_ratio);

loop_forward = plant_forward .* controller_forward;
loop_reverse = plant_reverse .* controller_reverse;
loop_z2p2_forward = plant_forward .* controller_z2p2_forward;
loop_z2p2_reverse = plant_reverse .* controller_z2p2_reverse;

[loop_crossover_forward_hz, phase_margin_forward_deg, ...
 gain_margin_forward_db] = ...
    analyze_loop_margins(control_frequency_hz, loop_forward);
[loop_crossover_reverse_hz, phase_margin_reverse_deg, ...
 gain_margin_reverse_db] = ...
    analyze_loop_margins(control_frequency_hz, loop_reverse);
[loop_crossover_z2p2_forward_hz, phase_margin_z2p2_forward_deg, ...
 gain_margin_z2p2_forward_db] = ...
    analyze_loop_margins(control_frequency_hz, loop_z2p2_forward);
[loop_crossover_z2p2_reverse_hz, phase_margin_z2p2_reverse_deg, ...
 gain_margin_z2p2_reverse_db] = ...
    analyze_loop_margins(control_frequency_hz, loop_z2p2_reverse);

plant_magnitude_db_forward = 20 .* log10(abs(plant_forward));
plant_phase_deg_forward = ...
    rad2deg(unwrap(angle(plant_forward), [], 1));
plant_magnitude_db_reverse = 20 .* log10(abs(plant_reverse));
plant_phase_deg_reverse = ...
    rad2deg(unwrap(angle(plant_reverse), [], 1));

controller_magnitude_db_forward = ...
    20 .* log10(abs(controller_forward));
controller_phase_deg_forward = ...
    rad2deg(unwrap(angle(controller_forward)));
controller_magnitude_db_reverse = ...
    20 .* log10(abs(controller_reverse));
controller_phase_deg_reverse = ...
    rad2deg(unwrap(angle(controller_reverse)));

controller_magnitude_db_z2p2_forward = ...
    20 .* log10(abs(controller_z2p2_forward));
controller_phase_deg_z2p2_forward = ...
    rad2deg(unwrap(angle(controller_z2p2_forward)));
controller_magnitude_db_z2p2_reverse = ...
    20 .* log10(abs(controller_z2p2_reverse));
controller_phase_deg_z2p2_reverse = ...
    rad2deg(unwrap(angle(controller_z2p2_reverse)));

loop_magnitude_db_forward = 20 .* log10(abs(loop_forward));
loop_phase_deg_forward = ...
    rad2deg(unwrap(angle(loop_forward), [], 1));
loop_magnitude_db_reverse = 20 .* log10(abs(loop_reverse));
loop_phase_deg_reverse = ...
    rad2deg(unwrap(angle(loop_reverse), [], 1));
loop_magnitude_db_z2p2_forward = ...
    20 .* log10(abs(loop_z2p2_forward));
loop_phase_deg_z2p2_forward = ...
    rad2deg(unwrap(angle(loop_z2p2_forward), [], 1));
loop_magnitude_db_z2p2_reverse = ...
    20 .* log10(abs(loop_z2p2_reverse));
loop_phase_deg_z2p2_reverse = ...
    rad2deg(unwrap(angle(loop_z2p2_reverse), [], 1));

%% 仅使用 2P2Z 与被控对象的闭环传递函数
closed_loop_z2p2_forward = ...
    loop_z2p2_forward ./ (1 + loop_z2p2_forward);
closed_loop_z2p2_reverse = ...
    loop_z2p2_reverse ./ (1 + loop_z2p2_reverse);

closed_loop_magnitude_db_forward = ...
    20 .* log10(abs(closed_loop_z2p2_forward));
closed_loop_phase_deg_forward = ...
    rad2deg(unwrap(angle(closed_loop_z2p2_forward), [], 1));
closed_loop_magnitude_db_reverse = ...
    20 .* log10(abs(closed_loop_z2p2_reverse));
closed_loop_phase_deg_reverse = ...
    rad2deg(unwrap(angle(closed_loop_z2p2_reverse), [], 1));

[closed_loop_bandwidth_forward_hz, closed_loop_peak_forward_db, ...
 closed_loop_peak_frequency_forward_hz] = analyze_closed_loop_metrics( ...
    control_frequency_hz, closed_loop_z2p2_forward);
[closed_loop_bandwidth_reverse_hz, closed_loop_peak_reverse_db, ...
 closed_loop_peak_frequency_reverse_hz] = analyze_closed_loop_metrics( ...
    control_frequency_hz, closed_loop_z2p2_reverse);

control_points_forward = table( ...
    power_w(:), frequency_forward_hz(:) / 1e3, ...
    Kvf_forward(:) * 1e3, output_tau_forward_s(:) * 1e3, ...
    loop_crossover_forward_hz(:) / 1e3, ...
    phase_margin_forward_deg(:), gain_margin_forward_db(:), ...
    (phase_margin_forward_deg(:) >= 45 & ...
     gain_margin_forward_db(:) >= 6), ...
    'VariableNames', { ...
        'Power_W', 'OperatingFrequency_kHz', ...
        'Kvf_V_per_kHz', 'OutputTimeConstant_ms', ...
        'LoopCrossover_kHz', 'PhaseMargin_deg', 'GainMargin_dB', ...
        'MeetsPM45_GM6'});

control_points_reverse = table( ...
    power_w(:), frequency_reverse_hz(:) / 1e3, ...
    Kvf_reverse(:) * 1e3, output_tau_reverse_s(:) * 1e3, ...
    loop_crossover_reverse_hz(:) / 1e3, ...
    phase_margin_reverse_deg(:), gain_margin_reverse_db(:), ...
    (phase_margin_reverse_deg(:) >= 45 & ...
     gain_margin_reverse_db(:) >= 6), ...
    'VariableNames', { ...
        'Power_W', 'OperatingFrequency_kHz', ...
        'Kvf_V_per_kHz', 'OutputTimeConstant_ms', ...
        'LoopCrossover_kHz', 'PhaseMargin_deg', 'GainMargin_dB', ...
        'MeetsPM45_GM6'});

controller_comparison_forward = table( ...
    power_w(:), ...
    loop_crossover_forward_hz(:) / 1e3, ...
    phase_margin_forward_deg(:), gain_margin_forward_db(:), ...
    (phase_margin_forward_deg(:) >= 45 & ...
     gain_margin_forward_db(:) >= 6), ...
    loop_crossover_z2p2_forward_hz(:) / 1e3, ...
    phase_margin_z2p2_forward_deg(:), ...
    gain_margin_z2p2_forward_db(:), ...
    (phase_margin_z2p2_forward_deg(:) >= 45 & ...
     gain_margin_z2p2_forward_db(:) >= 6), ...
    'VariableNames', { ...
        'Power_W', ...
        'PI_Crossover_kHz', 'PI_PM_deg', 'PI_GM_dB', 'PI_Meets', ...
        'Z2P2_Crossover_kHz', 'Z2P2_PM_deg', 'Z2P2_GM_dB', ...
        'Z2P2_Meets'});

controller_comparison_reverse = table( ...
    power_w(:), ...
    loop_crossover_reverse_hz(:) / 1e3, ...
    phase_margin_reverse_deg(:), gain_margin_reverse_db(:), ...
    (phase_margin_reverse_deg(:) >= 45 & ...
     gain_margin_reverse_db(:) >= 6), ...
    loop_crossover_z2p2_reverse_hz(:) / 1e3, ...
    phase_margin_z2p2_reverse_deg(:), ...
    gain_margin_z2p2_reverse_db(:), ...
    (phase_margin_z2p2_reverse_deg(:) >= 45 & ...
     gain_margin_z2p2_reverse_db(:) >= 6), ...
    'VariableNames', { ...
        'Power_W', ...
        'PI_Crossover_kHz', 'PI_PM_deg', 'PI_GM_dB', 'PI_Meets', ...
        'Z2P2_Crossover_kHz', 'Z2P2_PM_deg', 'Z2P2_GM_dB', ...
        'Z2P2_Meets'});

closed_loop_points_forward = table( ...
    power_w(:), closed_loop_bandwidth_forward_hz(:), ...
    closed_loop_peak_forward_db(:), ...
    closed_loop_peak_frequency_forward_hz(:), ...
    controller_comparison_forward.Z2P2_Meets, ...
    'VariableNames', { ...
        'Power_W', 'ClosedLoopBandwidth_Hz', ...
        'ClosedLoopPeak_dB', 'PeakFrequency_Hz', ...
        'OpenLoopMarginMeets'});

closed_loop_points_reverse = table( ...
    power_w(:), closed_loop_bandwidth_reverse_hz(:), ...
    closed_loop_peak_reverse_db(:), ...
    closed_loop_peak_frequency_reverse_hz(:), ...
    controller_comparison_reverse.Z2P2_Meets, ...
    'VariableNames', { ...
        'Power_W', 'ClosedLoopBandwidth_Hz', ...
        'ClosedLoopPeak_dB', 'PeakFrequency_Hz', ...
        'OpenLoopMarginMeets'});

fprintf('CLLC bidirectional FHA frequency-gain analysis\n');
fprintf('Turns ratio Np:Ns = %.0f:%.0f (n = %.3f)\n', Np, Ns, n);
fprintf('Primary series resonant frequency   = %.3f kHz\n', ...
        fr_primary_hz / 1e3);
fprintf('Secondary series resonant frequency = %.3f kHz\n', ...
        fr_secondary_hz / 1e3);
fprintf('\nForward %g V -> %g V: G = %.5f, M = %.5f\n', ...
        Vin_forward, Vout_forward, ...
        target_gain_dc_forward, target_gain_normalized_forward);
disp(operating_points_forward);
fprintf('\nReverse %g V -> %g V: G = %.5f, M = %.5f\n', ...
        Vin_reverse, Vout_reverse, ...
        target_gain_dc_reverse, target_gain_normalized_reverse);
fprintf(['NaN means that the target reverse gain is not reachable within ', ...
         'the ideal FHA model at that power.\n']);
disp(operating_points_reverse);
fprintf(['\nPFM loop model: FHA slope + output power-balance pole + ', ...
         '%.1f switching-cycle delay\n'], control_delay_cycles);
fprintf(['Forward PI designed at %g W: Kp = %.6g Hz/V, ', ...
         'Ki = %.6g Hz/(V*s)\n'], ...
        power_w(forward_design_index), Kp_forward, Ki_forward);
disp(control_points_forward);
fprintf(['Reverse PI designed at %g W: Kp = %.6g Hz/V, ', ...
         'Ki = %.6g Hz/(V*s)\n'], ...
        power_w(reverse_design_index), Kp_reverse, Ki_reverse);
disp(control_points_reverse);
fprintf(['\nForward 2P2Z at %g W: K = %.6g, fz = %.3f Hz, ', ...
         'fp = %.3f Hz, fc = %.3f Hz\n'], ...
        power_w(forward_design_index), K_z2p2_forward, ...
        fz_z2p2_forward_hz, fp_z2p2_forward_hz, ...
        crossover_z2p2_forward_hz);
disp(controller_comparison_forward);
fprintf(['Reverse 2P2Z at %g W: K = %.6g, fz = %.3f Hz, ', ...
         'fp = %.3f Hz, fc = %.3f Hz\n'], ...
        power_w(reverse_design_index), K_z2p2_reverse, ...
        fz_z2p2_reverse_hz, fp_z2p2_reverse_hz, ...
        crossover_z2p2_reverse_hz);
disp(controller_comparison_reverse);
fprintf('\nForward 2P2Z closed-loop characteristics\n');
disp(closed_loop_points_forward);
fprintf('Reverse 2P2Z closed-loop characteristics\n');
disp(closed_loop_points_reverse);

%% 绘制正向和反向频率增益曲线
figure('Color', 'w', 'Name', ...
       'CLLC bidirectional frequency gain versus output power');
layout = tiledlayout(2, 1, 'TileSpacing', 'compact', ...
                     'Padding', 'compact');

curve_colors = turbo(numel(power_w));

forward_axes = nexttile(layout);
hold(forward_axes, 'on');
grid(forward_axes, 'on');
box(forward_axes, 'on');
for k = 1:numel(power_w)
    plot(forward_axes, frequency_hz / 1e3, ...
        gain_normalized_forward(:, k), ...
        'LineWidth', 1.5, ...
        'Color', curve_colors(k, :), ...
        'DisplayName', sprintf('%g W', power_w(k)));
end

xline(forward_axes, fr_primary_hz / 1e3, '--k', ...
    sprintf('f_r = %.2f kHz', fr_primary_hz / 1e3), ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');
yline(forward_axes, target_gain_normalized_forward, ':k', ...
    sprintf('M_{target} = %.3f', target_gain_normalized_forward), ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

xlabel(forward_axes, 'Switching frequency / kHz');
ylabel(forward_axes, 'M_{forward} = nV_{out}/V_{in}');
title(forward_axes, sprintf('Forward: %.0f V \\rightarrow %.0f V', ...
      Vin_forward, Vout_forward));
legend(forward_axes, 'Location', 'eastoutside');
xlim(forward_axes, forward_plot_range_hz / 1e3);

reverse_axes = nexttile(layout);
hold(reverse_axes, 'on');
grid(reverse_axes, 'on');
box(reverse_axes, 'on');
for k = 1:numel(power_w)
    semilogy(reverse_axes, frequency_hz / 1e3, ...
        gain_normalized_reverse(:, k), ...
        'LineWidth', 1.5, ...
        'Color', curve_colors(k, :), ...
        'DisplayName', sprintf('%g W', power_w(k)));
end
set(reverse_axes, 'YScale', 'log');

xline(reverse_axes, fr_primary_hz / 1e3, '--k', ...
    sprintf('f_r = %.2f kHz', fr_primary_hz / 1e3), ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');
yline(reverse_axes, target_gain_normalized_reverse, ':k', ...
    sprintf('M_{target} = %.3f', target_gain_normalized_reverse), ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

xlabel(reverse_axes, 'Switching frequency / kHz');
ylabel(reverse_axes, 'M_{reverse} = V_{out}/(nV_{in})');
title(reverse_axes, sprintf('Reverse: %.0f V \\rightarrow %.0f V', ...
      Vin_reverse, Vout_reverse));
xlim(reverse_axes, reverse_plot_range_hz / 1e3);
ylim(reverse_axes, [5e-2, 5e1]);

title(layout, 'CLLC bidirectional FHA frequency gain');

%% 绘制控制器、被控对象与开环波特图
% 横轴是施加在频率指令上的小信号扰动频率，不是开关频率。
plot_control_loop_bode( ...
    'Forward PFM control loop', control_frequency_hz, ...
    plant_magnitude_db_forward, plant_phase_deg_forward, ...
    controller_magnitude_db_forward, controller_phase_deg_forward, ...
    loop_magnitude_db_forward, loop_phase_deg_forward, ...
    power_w, Rload_dc_forward, control_plot_range_hz, ...
    controller_crossover_hz, curve_colors);

plot_control_loop_bode( ...
    'Reverse PFM control loop', control_frequency_hz, ...
    plant_magnitude_db_reverse, plant_phase_deg_reverse, ...
    controller_magnitude_db_reverse, controller_phase_deg_reverse, ...
    loop_magnitude_db_reverse, loop_phase_deg_reverse, ...
    power_w, Rload_dc_reverse, control_plot_range_hz, ...
    controller_crossover_hz, curve_colors);

plot_controller_comparison( ...
    'Forward PI versus 2P2Z', control_frequency_hz, ...
    controller_magnitude_db_forward, controller_phase_deg_forward, ...
    controller_magnitude_db_z2p2_forward, ...
    controller_phase_deg_z2p2_forward, ...
    loop_magnitude_db_forward(:, forward_design_index), ...
    loop_phase_deg_forward(:, forward_design_index), ...
    loop_magnitude_db_z2p2_forward(:, forward_design_index), ...
    loop_phase_deg_z2p2_forward(:, forward_design_index), ...
    controller_comparison_forward, control_plot_range_hz, ...
    controller_crossover_hz, crossover_z2p2_forward_hz);

plot_controller_comparison( ...
    'Reverse PI versus 2P2Z', control_frequency_hz, ...
    controller_magnitude_db_reverse, controller_phase_deg_reverse, ...
    controller_magnitude_db_z2p2_reverse, ...
    controller_phase_deg_z2p2_reverse, ...
    loop_magnitude_db_reverse(:, reverse_design_index), ...
    loop_phase_deg_reverse(:, reverse_design_index), ...
    loop_magnitude_db_z2p2_reverse(:, reverse_design_index), ...
    loop_phase_deg_z2p2_reverse(:, reverse_design_index), ...
    controller_comparison_reverse, control_plot_range_hz, ...
    controller_crossover_hz, crossover_z2p2_reverse_hz);

plot_z2p2_closed_loop_bode( ...
    'Forward 2P2Z closed loop', control_frequency_hz, ...
    closed_loop_magnitude_db_forward, ...
    closed_loop_phase_deg_forward, power_w, Rload_dc_forward, ...
    control_plot_range_hz, curve_colors);

plot_z2p2_closed_loop_bode( ...
    'Reverse 2P2Z closed loop', control_frequency_hz, ...
    closed_loop_magnitude_db_reverse, ...
    closed_loop_phase_deg_reverse, power_w, Rload_dc_reverse, ...
    control_plot_range_hz, curve_colors);

% 将主要结果保留在工作区，便于后续控制器设计或数据导出。
results.frequency_hz = frequency_hz;
results.control_frequency_hz = control_frequency_hz;
results.power_w = power_w;
results.primary_resonant_frequency_hz = fr_primary_hz;
results.secondary_resonant_frequency_hz = fr_secondary_hz;
results.forward.gain_dc = gain_dc_forward;
results.forward.gain_normalized = gain_normalized_forward;
results.forward.operating_points = operating_points_forward;
results.forward.control.plant = plant_forward;
results.forward.control.controller = controller_forward;
results.forward.control.loop_gain = loop_forward;
results.forward.control.Kp = Kp_forward;
results.forward.control.Ki = Ki_forward;
results.forward.control.points = control_points_forward;
results.forward.control.z2p2.K = K_z2p2_forward;
results.forward.control.z2p2.fz_hz = fz_z2p2_forward_hz;
results.forward.control.z2p2.fp_hz = fp_z2p2_forward_hz;
results.forward.control.z2p2.design_crossover_hz = ...
    crossover_z2p2_forward_hz;
results.forward.control.z2p2.controller = controller_z2p2_forward;
results.forward.control.z2p2.loop_gain = loop_z2p2_forward;
results.forward.control.z2p2.closed_loop = closed_loop_z2p2_forward;
results.forward.control.z2p2.closed_loop_points = ...
    closed_loop_points_forward;
results.forward.control.comparison = controller_comparison_forward;
results.reverse.gain_dc = gain_dc_reverse;
results.reverse.gain_normalized = gain_normalized_reverse;
results.reverse.operating_points = operating_points_reverse;
results.reverse.control.plant = plant_reverse;
results.reverse.control.controller = controller_reverse;
results.reverse.control.loop_gain = loop_reverse;
results.reverse.control.Kp = Kp_reverse;
results.reverse.control.Ki = Ki_reverse;
results.reverse.control.points = control_points_reverse;
results.reverse.control.z2p2.K = K_z2p2_reverse;
results.reverse.control.z2p2.fz_hz = fz_z2p2_reverse_hz;
results.reverse.control.z2p2.fp_hz = fp_z2p2_reverse_hz;
results.reverse.control.z2p2.design_crossover_hz = ...
    crossover_z2p2_reverse_hz;
results.reverse.control.z2p2.controller = controller_z2p2_reverse;
results.reverse.control.z2p2.loop_gain = loop_z2p2_reverse;
results.reverse.control.z2p2.closed_loop = closed_loop_z2p2_reverse;
results.reverse.control.z2p2.closed_loop_points = ...
    closed_loop_points_reverse;
results.reverse.control.comparison = controller_comparison_reverse;

%% 局部函数
function crossing_hz = find_gain_crossing( ...
    frequency_hz, gain, target, fr_hz, frequency_side)
%FIND_GAIN_CROSSING 查找最接近串联谐振点的目标增益交点。

    if strcmp(frequency_side, 'above')
        valid_index = find(frequency_hz >= fr_hz);
    elseif strcmp(frequency_side, 'below')
        valid_index = flip(find(frequency_hz <= fr_hz));
    else
        error('frequency_side must be ''above'' or ''below''.');
    end

    error_from_target = gain(valid_index) - target;
    crossing_pair = find( ...
        error_from_target(1:end-1) .* error_from_target(2:end) <= 0, ...
        1, 'first');

    if isempty(crossing_pair)
        crossing_hz = NaN;
        return;
    end

    index_1 = valid_index(crossing_pair);
    index_2 = valid_index(crossing_pair + 1);
    frequency_pair = frequency_hz([index_1, index_2]);
    gain_pair = gain([index_1, index_2]);

    if gain_pair(1) == gain_pair(2)
        crossing_hz = frequency_pair(1);
    else
        crossing_hz = frequency_pair(1) + ...
            (target - gain_pair(1)) * ...
            (frequency_pair(2) - frequency_pair(1)) / ...
            (gain_pair(2) - gain_pair(1));
    end
end

function [plant, Kvf, output_tau_s] = build_pfm_control_plant( ...
    control_frequency_hz, switching_frequency_hz, ...
    static_output_voltage, operating_frequency_hz, ...
    load_resistance, output_capacitance, delay_cycles)
%BUILD_PFM_CONTROL_PLANT 建立频率控制到输出电压的低频包络模型。
%
% 功率平衡线性化模型：
%   Gvf(s) = (-Kvf) / (1 + s*Rload*Cout/2) * exp(-s*Td)
%
% Kvf = dVout/dfs。负号来自 fs = fs_bias - controller_output 的执行
% 方向；Td 使用若干个开关周期近似数字更新和调制延迟。

    s = 1j .* 2 .* pi .* control_frequency_hz(:);
    load_count = numel(load_resistance);
    plant = complex(nan(numel(s), load_count));
    Kvf = nan(1, load_count);
    output_tau_s = load_resistance .* output_capacitance ./ 2;

    for k = 1:load_count
        if ~isfinite(operating_frequency_hz(k))
            continue;
        end

        voltage_slope = gradient( ...
            static_output_voltage(:, k), switching_frequency_hz(:));
        Kvf(k) = interp1( ...
            switching_frequency_hz, voltage_slope, ...
            operating_frequency_hz(k), 'linear');

        delay_s = delay_cycles / operating_frequency_hz(k);
        plant(:, k) = (-Kvf(k)) ./ ...
            (1 + s .* output_tau_s(k)) .* exp(-s .* delay_s);
    end
end

function [Kp, Ki, controller] = design_pi_controller( ...
    frequency_hz, design_plant, crossover_hz, zero_ratio)
%DESIGN_PI_CONTROLLER 按论文式 (16) 的零点比例和 0 dB 条件整定 PI。

    plant_gain_at_crossover = interp1( ...
        log10(frequency_hz), abs(design_plant), ...
        log10(crossover_hz), 'linear');
    zero_hz = zero_ratio .* crossover_hz;
    pi_shape_gain = sqrt(1 + (zero_hz / crossover_hz)^2);

    Kp = 1 / (plant_gain_at_crossover .* pi_shape_gain);
    Ki = 2 .* pi .* zero_hz .* Kp;

    s = 1j .* 2 .* pi .* frequency_hz(:);
    controller = Kp + Ki ./ s;
end

function [K, zero_hz, pole_hz, controller, selected_crossover_hz] = ...
    design_z2p2_controller( ...
        frequency_hz, design_plant, maximum_crossover_hz, ...
        design_output_tau_s, operating_frequency_hz, ...
        target_phase_margin_deg, target_gain_margin_db, ...
        minimum_crossover_ratio, max_pole_fs_ratio)
%DESIGN_Z2P2_CONTROLLER 设计与 code/lib/z2p2 参数形式一致的控制器。
%
% 连续域原型：
%   Gc(s) = K*(1+s/wz)^2 / (s*(1+s/wp)^2)
%
% 两个重合零点放在设计负载输出极点处。函数从 PI 的目标交越频率
% 向下搜索，选择同时满足 PM 和 GM 目标的最高交越频率。

    zero_hz = 1 ./ (2 .* pi .* design_output_tau_s);
    valid_operating_frequency_hz = operating_frequency_hz( ...
        isfinite(operating_frequency_hz));
    crossover_candidates_hz = logspace( ...
        log10(maximum_crossover_hz), ...
        log10(maximum_crossover_hz .* minimum_crossover_ratio), 41);

    for candidate_index = 1:numel(crossover_candidates_hz)
        candidate_crossover_hz = ...
            crossover_candidates_hz(candidate_index);
        [candidate_K, candidate_pole_hz, candidate_controller] = ...
            synthesize_z2p2_at_crossover( ...
                frequency_hz, design_plant, candidate_crossover_hz, ...
                zero_hz, valid_operating_frequency_hz, ...
                target_phase_margin_deg, max_pole_fs_ratio);

        candidate_loop = design_plant .* candidate_controller;
        [~, candidate_pm_deg, candidate_gm_db] = ...
            analyze_loop_margins(frequency_hz, candidate_loop);

        K = candidate_K;
        pole_hz = candidate_pole_hz;
        controller = candidate_controller;
        selected_crossover_hz = candidate_crossover_hz;

        if candidate_pm_deg >= target_phase_margin_deg && ...
           candidate_gm_db >= target_gain_margin_db
            return;
        end
    end
end

function [K, pole_hz, controller] = synthesize_z2p2_at_crossover( ...
    frequency_hz, design_plant, crossover_hz, zero_hz, ...
    valid_operating_frequency_hz, target_phase_margin_deg, ...
    max_pole_fs_ratio)
%SYNTHESIZE_Z2P2_AT_CROSSOVER 在指定交越频率下求 2P2Z 极点和增益。

    maximum_pole_hz = max(crossover_hz, ...
        max_pole_fs_ratio .* min(valid_operating_frequency_hz));
    plant_phase_deg = rad2deg(unwrap(angle(design_plant)));
    plant_phase_at_crossover_deg = interp1( ...
        log10(frequency_hz), plant_phase_deg, ...
        log10(crossover_hz), 'linear');
    required_controller_phase_deg = ...
        -180 + target_phase_margin_deg - ...
        plant_phase_at_crossover_deg;

    zero_phase_deg = 2 .* atand(crossover_hz ./ zero_hz);
    required_pole_angle_deg = ...
        (-90 + zero_phase_deg - required_controller_phase_deg) ./ 2;
    minimum_pole_angle_deg = atand(crossover_hz ./ maximum_pole_hz);
    pole_angle_deg = min(max(required_pole_angle_deg, ...
        minimum_pole_angle_deg), 45);
    pole_hz = crossover_hz ./ tand(pole_angle_deg);

    s = 1j .* 2 .* pi .* frequency_hz(:);
    base_controller = ...
        (1 + s ./ (2 .* pi .* zero_hz)).^2 ./ ...
        (s .* (1 + s ./ (2 .* pi .* pole_hz)).^2);
    plant_gain_at_crossover = interp1( ...
        log10(frequency_hz), abs(design_plant), ...
        log10(crossover_hz), 'linear');
    base_gain_at_crossover = interp1( ...
        log10(frequency_hz), abs(base_controller), ...
        log10(crossover_hz), 'linear');
    K = 1 ./ (plant_gain_at_crossover .* base_gain_at_crossover);
    controller = K .* base_controller;
end

function [crossover_hz, phase_margin_deg, gain_margin_db] = ...
    analyze_loop_margins(frequency_hz, loop_gain)
%ANALYZE_LOOP_MARGINS 计算每个负载下的交越频率、相位裕度和增益裕度。

    load_count = size(loop_gain, 2);
    crossover_hz = nan(1, load_count);
    phase_margin_deg = nan(1, load_count);
    gain_margin_db = nan(1, load_count);

    magnitude_db = 20 .* log10(abs(loop_gain));
    phase_deg = rad2deg(unwrap(angle(loop_gain), [], 1));

    for k = 1:load_count
        valid = isfinite(magnitude_db(:, k)) & ...
                isfinite(phase_deg(:, k));
        if nnz(valid) < 2
            continue;
        end

        frequency_valid = frequency_hz(valid);
        magnitude_valid = magnitude_db(valid, k);
        phase_valid = phase_deg(valid, k);

        gain_crossings_hz = find_log_crossings( ...
            frequency_valid, magnitude_valid, 0);
        if ~isempty(gain_crossings_hz)
            phase_at_crossings = interp1( ...
                log10(frequency_valid), phase_valid, ...
                log10(gain_crossings_hz), 'linear');
            phase_margins = 180 + phase_at_crossings;
            [phase_margin_deg(k), critical_crossing_index] = ...
                min(phase_margins);
            crossover_hz(k) = ...
                gain_crossings_hz(critical_crossing_index);
        end

        phase_crossings_hz = find_log_crossings( ...
            frequency_valid, phase_valid, -180);
        if ~isempty(phase_crossings_hz)
            magnitude_at_phase_crossings = interp1( ...
                log10(frequency_valid), magnitude_valid, ...
                log10(phase_crossings_hz), 'linear');
            gain_margin_db(k) = min(-magnitude_at_phase_crossings);
        else
            gain_margin_db(k) = Inf;
        end
    end
end

function crossings_hz = find_log_crossings(frequency_hz, value, target)
%FIND_LOG_CROSSINGS 在对数频率坐标中插值全部目标交点。

    difference = value - target;
    crossing_pairs = find( ...
        difference(1:end-1) .* difference(2:end) <= 0);

    if isempty(crossing_pairs)
        crossings_hz = [];
        return;
    end

    crossings_hz = nan(size(crossing_pairs));
    for k = 1:numel(crossing_pairs)
        crossing_pair = crossing_pairs(k);
        value_1 = value(crossing_pair);
        value_2 = value(crossing_pair + 1);
        log_frequency_1 = log10(frequency_hz(crossing_pair));
        log_frequency_2 = log10(frequency_hz(crossing_pair + 1));

        if value_1 == value_2
            crossings_hz(k) = 10^log_frequency_1;
        else
            interpolation_ratio = (target - value_1) / ...
                                  (value_2 - value_1);
            crossings_hz(k) = 10^(log_frequency_1 + ...
                interpolation_ratio * ...
                (log_frequency_2 - log_frequency_1));
        end
    end
end

function [bandwidth_hz, peak_db, peak_frequency_hz] = ...
    analyze_closed_loop_metrics(frequency_hz, closed_loop)
%ANALYZE_CLOSED_LOOP_METRICS 计算闭环 -3 dB 带宽和谐振峰值。

    load_count = size(closed_loop, 2);
    bandwidth_hz = nan(1, load_count);
    peak_db = nan(1, load_count);
    peak_frequency_hz = nan(1, load_count);

    magnitude_db = 20 .* log10(abs(closed_loop));
    for k = 1:load_count
        valid = isfinite(magnitude_db(:, k));
        if nnz(valid) < 2
            continue;
        end

        frequency_valid = frequency_hz(valid);
        magnitude_valid = magnitude_db(valid, k);
        [peak_db(k), peak_index] = max(magnitude_valid);
        peak_frequency_hz(k) = frequency_valid(peak_index);

        low_frequency_gain_db = magnitude_valid(1);
        bandwidth_target_db = low_frequency_gain_db - 3;
        post_peak_frequency_hz = frequency_valid(peak_index:end);
        post_peak_magnitude_db = magnitude_valid(peak_index:end);
        bandwidth_crossings_hz = find_log_crossings( ...
            post_peak_frequency_hz, post_peak_magnitude_db, ...
            bandwidth_target_db);
        if ~isempty(bandwidth_crossings_hz)
            bandwidth_hz(k) = bandwidth_crossings_hz(1);
        end
    end
end

function plot_control_loop_bode( ...
    figure_title, frequency_hz, ...
    plant_magnitude_db, plant_phase_deg, ...
    controller_magnitude_db, controller_phase_deg, ...
    loop_magnitude_db, loop_phase_deg, ...
    power_w, load_resistance, plot_range_hz, ...
    target_crossover_hz, curve_colors)
%PLOT_CONTROL_LOOP_BODE 分别绘制被控对象、PI 控制器和开环波特图。

    figure('Color', 'w', 'Name', figure_title);
    layout = tiledlayout(2, 3, 'TileSpacing', 'compact', ...
                         'Padding', 'compact');

    plant_magnitude_axes = nexttile(layout, 1);
    controller_magnitude_axes = nexttile(layout, 2);
    loop_magnitude_axes = nexttile(layout, 3);
    plant_phase_axes = nexttile(layout, 4);
    controller_phase_axes = nexttile(layout, 5);
    loop_phase_axes = nexttile(layout, 6);

    all_axes = [plant_magnitude_axes, controller_magnitude_axes, ...
                loop_magnitude_axes, plant_phase_axes, ...
                controller_phase_axes, loop_phase_axes];
    for axes_handle = all_axes
        hold(axes_handle, 'on');
        grid(axes_handle, 'on');
        box(axes_handle, 'on');
        set(axes_handle, 'XScale', 'log');
        xlim(axes_handle, plot_range_hz);
    end

    for k = 1:numel(power_w)
        if ~any(isfinite(plant_magnitude_db(:, k)))
            continue;
        end

        display_name = sprintf('%g W (%.3g Ohm)', ...
            power_w(k), load_resistance(k));
        semilogx(plant_magnitude_axes, frequency_hz, ...
            plant_magnitude_db(:, k), ...
            'LineWidth', 1.4, 'Color', curve_colors(k, :), ...
            'DisplayName', display_name);
        semilogx(plant_phase_axes, frequency_hz, ...
            plant_phase_deg(:, k), ...
            'LineWidth', 1.4, 'Color', curve_colors(k, :));
        semilogx(loop_magnitude_axes, frequency_hz, ...
            loop_magnitude_db(:, k), ...
            'LineWidth', 1.4, 'Color', curve_colors(k, :));
        semilogx(loop_phase_axes, frequency_hz, ...
            loop_phase_deg(:, k), ...
            'LineWidth', 1.4, 'Color', curve_colors(k, :));
    end

    semilogx(controller_magnitude_axes, frequency_hz, ...
        controller_magnitude_db, 'k', 'LineWidth', 1.6);
    semilogx(controller_phase_axes, frequency_hz, ...
        controller_phase_deg, 'k', 'LineWidth', 1.6);

    yline(loop_magnitude_axes, 0, ':k');
    yline(loop_phase_axes, -180, ':k');
    xline(loop_magnitude_axes, target_crossover_hz, '--k');
    xline(loop_phase_axes, target_crossover_hz, '--k');

    title(plant_magnitude_axes, 'Plant G_{vf}(s)');
    title(controller_magnitude_axes, 'PI controller G_c(s)');
    title(loop_magnitude_axes, 'Open loop T(s) = G_cG_{vf}');
    ylabel(plant_magnitude_axes, 'Magnitude / dB');
    ylabel(plant_phase_axes, 'Phase / degree');
    xlabel(plant_phase_axes, 'Perturbation frequency / Hz');
    xlabel(controller_phase_axes, 'Perturbation frequency / Hz');
    xlabel(loop_phase_axes, 'Perturbation frequency / Hz');
    legend(plant_magnitude_axes, 'Location', 'best');
    title(layout, figure_title);
end

function plot_controller_comparison( ...
    figure_title, frequency_hz, ...
    pi_magnitude_db, pi_phase_deg, ...
    z2p2_magnitude_db, z2p2_phase_deg, ...
    pi_loop_magnitude_db, pi_loop_phase_deg, ...
    z2p2_loop_magnitude_db, z2p2_loop_phase_deg, ...
    comparison_table, plot_range_hz, target_crossover_hz, ...
    z2p2_crossover_hz)
%PLOT_CONTROLLER_COMPARISON 对比 PI 与 2P2Z 的设计点波特图和负载裕度。

    figure('Color', 'w', 'Name', figure_title);
    layout = tiledlayout(2, 3, 'TileSpacing', 'compact', ...
                         'Padding', 'compact');

    controller_magnitude_axes = nexttile(layout, 1);
    loop_magnitude_axes = nexttile(layout, 2);
    phase_margin_axes = nexttile(layout, 3);
    controller_phase_axes = nexttile(layout, 4);
    loop_phase_axes = nexttile(layout, 5);
    gain_margin_axes = nexttile(layout, 6);

    frequency_axes = [controller_magnitude_axes, loop_magnitude_axes, ...
                      controller_phase_axes, loop_phase_axes];
    for axes_handle = frequency_axes
        hold(axes_handle, 'on');
        grid(axes_handle, 'on');
        box(axes_handle, 'on');
        set(axes_handle, 'XScale', 'log');
        xlim(axes_handle, plot_range_hz);
    end

    semilogx(controller_magnitude_axes, frequency_hz, ...
        pi_magnitude_db, '--', 'LineWidth', 1.6, ...
        'DisplayName', 'PI');
    semilogx(controller_magnitude_axes, frequency_hz, ...
        z2p2_magnitude_db, '-', 'LineWidth', 1.6, ...
        'DisplayName', '2P2Z');
    semilogx(controller_phase_axes, frequency_hz, ...
        pi_phase_deg, '--', 'LineWidth', 1.6);
    semilogx(controller_phase_axes, frequency_hz, ...
        z2p2_phase_deg, '-', 'LineWidth', 1.6);

    semilogx(loop_magnitude_axes, frequency_hz, ...
        pi_loop_magnitude_db, '--', 'LineWidth', 1.6, ...
        'DisplayName', 'PI + plant');
    semilogx(loop_magnitude_axes, frequency_hz, ...
        z2p2_loop_magnitude_db, '-', 'LineWidth', 1.6, ...
        'DisplayName', '2P2Z + plant');
    semilogx(loop_phase_axes, frequency_hz, ...
        pi_loop_phase_deg, '--', 'LineWidth', 1.6);
    semilogx(loop_phase_axes, frequency_hz, ...
        z2p2_loop_phase_deg, '-', 'LineWidth', 1.6);

    yline(loop_magnitude_axes, 0, ':k', 'HandleVisibility', 'off');
    yline(loop_phase_axes, -180, ':k', 'HandleVisibility', 'off');
    xline(loop_magnitude_axes, target_crossover_hz, ':', ...
        'PI f_c', 'Color', [0 0.4470 0.7410], ...
        'HandleVisibility', 'off');
    xline(loop_magnitude_axes, z2p2_crossover_hz, ':', ...
        '2P2Z f_c', 'Color', [0.8500 0.3250 0.0980], ...
        'HandleVisibility', 'off');
    xline(loop_phase_axes, target_crossover_hz, ':', ...
        'Color', [0 0.4470 0.7410], ...
        'HandleVisibility', 'off');
    xline(loop_phase_axes, z2p2_crossover_hz, ':', ...
        'Color', [0.8500 0.3250 0.0980], ...
        'HandleVisibility', 'off');

    hold(phase_margin_axes, 'on');
    grid(phase_margin_axes, 'on');
    box(phase_margin_axes, 'on');
    plot(phase_margin_axes, comparison_table.Power_W, ...
        comparison_table.PI_PM_deg, 'o--', 'LineWidth', 1.4, ...
        'DisplayName', 'PI');
    plot(phase_margin_axes, comparison_table.Power_W, ...
        comparison_table.Z2P2_PM_deg, 's-', 'LineWidth', 1.4, ...
        'DisplayName', '2P2Z');
    yline(phase_margin_axes, 45, ':k', 'PM = 45 deg', ...
        'HandleVisibility', 'off');

    hold(gain_margin_axes, 'on');
    grid(gain_margin_axes, 'on');
    box(gain_margin_axes, 'on');
    plot(gain_margin_axes, comparison_table.Power_W, ...
        comparison_table.PI_GM_dB, 'o--', 'LineWidth', 1.4);
    plot(gain_margin_axes, comparison_table.Power_W, ...
        comparison_table.Z2P2_GM_dB, 's-', 'LineWidth', 1.4);
    yline(gain_margin_axes, 6, ':k', 'GM = 6 dB', ...
        'HandleVisibility', 'off');

    title(controller_magnitude_axes, 'Controller');
    title(loop_magnitude_axes, 'Open loop at design load');
    title(phase_margin_axes, 'Phase margin versus power');
    title(controller_phase_axes, 'Controller phase');
    title(loop_phase_axes, 'Open-loop phase at design load');
    title(gain_margin_axes, 'Gain margin versus power');
    ylabel(controller_magnitude_axes, 'Magnitude / dB');
    ylabel(controller_phase_axes, 'Phase / degree');
    ylabel(phase_margin_axes, 'PM / degree');
    ylabel(gain_margin_axes, 'GM / dB');
    xlabel(controller_phase_axes, 'Perturbation frequency / Hz');
    xlabel(loop_phase_axes, 'Perturbation frequency / Hz');
    xlabel(phase_margin_axes, 'Output power / W');
    xlabel(gain_margin_axes, 'Output power / W');
    legend(controller_magnitude_axes, 'Location', 'best');
    legend(loop_magnitude_axes, 'Location', 'best');
    legend(phase_margin_axes, 'Location', 'best');
    title(layout, figure_title);
end

function plot_z2p2_closed_loop_bode( ...
    figure_title, frequency_hz, magnitude_db, phase_deg, ...
    power_w, load_resistance, plot_range_hz, curve_colors)
%PLOT_Z2P2_CLOSED_LOOP_BODE 绘制纯 2P2Z 闭环参考到输出频响。

    figure('Color', 'w', 'Name', figure_title);
    layout = tiledlayout(2, 1, 'TileSpacing', 'compact', ...
                         'Padding', 'compact');
    magnitude_axes = nexttile(layout, 1);
    phase_axes = nexttile(layout, 2);

    for axes_handle = [magnitude_axes, phase_axes]
        hold(axes_handle, 'on');
        grid(axes_handle, 'on');
        box(axes_handle, 'on');
        set(axes_handle, 'XScale', 'log');
        xlim(axes_handle, plot_range_hz);
    end

    for k = 1:numel(power_w)
        if ~any(isfinite(magnitude_db(:, k)))
            continue;
        end

        display_name = sprintf('%g W (%.3g Ohm)', ...
            power_w(k), load_resistance(k));
        semilogx(magnitude_axes, frequency_hz, magnitude_db(:, k), ...
            'LineWidth', 1.5, 'Color', curve_colors(k, :), ...
            'DisplayName', display_name);
        semilogx(phase_axes, frequency_hz, phase_deg(:, k), ...
            'LineWidth', 1.5, 'Color', curve_colors(k, :));
    end

    yline(magnitude_axes, -3, ':k', '-3 dB', ...
        'HandleVisibility', 'off');
    ylabel(magnitude_axes, 'Magnitude / dB');
    ylabel(phase_axes, 'Phase / degree');
    xlabel(phase_axes, 'Perturbation frequency / Hz');
    title(magnitude_axes, ...
        'G_{cl}(s) = G_{2P2Z}(s)G_{vf}(s) / [1 + G_{2P2Z}(s)G_{vf}(s)]');
    legend(magnitude_axes, 'Location', 'eastoutside');
    title(layout, figure_title);
end
