function create_topology()
%CREATE_TOPOLOGY Create a simple PLL test model.
%
% Run this script from MATLAB:
%   cd <repo_root>/matlab/pll
%   compile
%   create_topology

model = 'pll_mod';

if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);
open_system(model);

set_param(model, ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '4.0e-6', ...
    'StopTime', '0.2');

compileCallback = [
    "currDir = pwd;" newline ...
    "projectDir = fileparts(get_param(bdroot, 'FileName'));" newline ...
    "cd(projectDir);" newline ...
    "clear mex;" newline ...
    "compile;" newline ...
    "cd(currDir);"];

set_param(model, 'InitFcn', compileCallback);

add_block('simulink/Sources/Sine Wave', [model, '/v_a'], ...
    'Amplitude', '311', ...
    'Frequency', '2*pi*50', ...
    'Phase', 'pi/2', ...
    'Position', [80, 60, 150, 90]);

add_block('simulink/Sources/Sine Wave', [model, '/v_b'], ...
    'Amplitude', '311', ...
    'Frequency', '2*pi*50', ...
    'Phase', 'pi/2 - 2*pi/3', ...
    'Position', [80, 130, 150, 160]);

add_block('simulink/Sources/Sine Wave', [model, '/v_c'], ...
    'Amplitude', '311', ...
    'Frequency', '2*pi*50', ...
    'Phase', 'pi/2 + 2*pi/3', ...
    'Position', [80, 200, 150, 230]);

add_block('simulink/Signal Routing/Mux', [model, '/abc'], ...
    'Inputs', '3', ...
    'Position', [220, 95, 250, 195]);

add_block('simulink/User-Defined Functions/S-Function', [model, '/pll_sfunc'], ...
    'FunctionName', 'sfunc', ...
    'Position', [320, 120, 430, 170]);

add_block('simulink/Signal Routing/Demux', [model, '/pll_outputs'], ...
    'Outputs', '22', ...
    'Position', [500, 120, 530, 170]);

add_block('simulink/Sinks/To Workspace', [model, '/pll_loop'], ...
    'VariableName', 'pll_loop', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [500, 220, 590, 250]);

add_block('simulink/Sinks/To Workspace', [model, '/omega'], ...
    'VariableName', 'pll_omega', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [610, 105, 700, 135]);

add_block('simulink/Sinks/To Workspace', [model, '/theta'], ...
    'VariableName', 'pll_theta', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [610, 160, 700, 190]);

add_line(model, 'v_a/1', 'abc/1');
add_line(model, 'v_b/1', 'abc/2');
add_line(model, 'v_c/1', 'abc/3');
add_line(model, 'abc/1', 'pll_sfunc/1');
add_line(model, 'pll_sfunc/1', 'pll_outputs/1');
add_line(model, 'pll_sfunc/1', 'pll_loop/1', 'autorouting', 'on');
add_line(model, 'pll_outputs/1', 'omega/1');
add_line(model, 'pll_outputs/2', 'theta/1');

save_system(model, fullfile(fileparts(mfilename('fullpath')), [model, '.slx']));
end
